### ISSUE TITLE
Is there a way to know if the canvas was invalidate?

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgrabitmap#126]
Hello.

I use BGRABitmap for a animation.

The timer is in fact a loop that catch a chunk of the sound data, translate it into samples and sent it to the audio-card and the canvas is invalidated inside the loop.

It is perfect if the canvas is little (no more than 500x500 pixels) but in full screen the "timer-interval" of the audio-loop is too short, so some canvas is not invalidated during the loop.

Is it possible to know the time needed to invalidate a canvas and then adapt in the audio-loop when a new canvas is ready to be invalidated?

Thanks.

Fre;D

**Comment by circular17** [comment]
Sorry but I am not sure I understand.

Do you mean that there is not enough time to repaint the form?

**Comment by circular17** [comment]
Ok. Invalidating in itself takes no time. Painting can take time. If you are drawing in the OnPaint event, then you can set a boolean there to True to know it has been repainted. And set this boolean to False when you invalidate.

**Comment by fredvs** [comment]
Ha, ok, perfect.
Many thanks.

**Comment by fredvs** [comment]
Hu, no sorry, there is still problems (and surely I miss something).

In the main loop of a thread (a audio loop), at each loop some variables are filled and a call to aform.invalidate is done (and this does a re-painted according to the new value).

Should I use instead aform.onpaint without invalidate?

If so, how to set the is_buzy_to_draw boolean?

At the begining of the onpaint even, set it to true and at end set it to false?

And then in the main loop use:

if is_buzy_to_draw = false then aform.onpaint ?

**Comment by circular17** [comment]
The OnPaint event should not be called directly and only triggered indirectly by Invalidate.

Setting the boolean to True and then False within the OnPaint event would make sense only in a multithread context. Otherwise, from outside the procedure, the value would always be False.

**Comment by fredvs** [comment]
Ok, ok, ok, I will try with a other thread then.

So to resume, 1 main-thread, 1 audio-thread and 1 animation-thread.

Write you later.

**Comment by fredvs** [comment]
Hello.

OK, I am inside threads.

But I am still not sure if what I do is ok.
All works ok, but I noted that fs the animation (that I think is part of a independent thread) is in full screen, of course the animation is slower, but all the others animations that are part of the main thread, like view meters or position are slower too.

I was thinking that the speed of animation in other threads would not be affected by the animation on the full screen but it does.

Anyway, here how I did:

In the form of the animation (it uses `msethreads`):

```

var
evPause: PRTLEvent;// for pausing
status : integer = -1; // to stop

type
  tanimfo = class(tdockform)
   tpaintbox1: tpaintbox;
   procedure oncreate(const sender: TObject);
   procedure onpaint(const Sender: twidget;
                   const acanvas: tcanvas);
 ...
   protected
     thethread : tmsethread; 
     function execute(thread: tmsethread): integer;
   end;

 procedure tanilmfo.oncreate(const sender: TObject);
begin
 evPauseImage := RTLEventCreate;
 thethread:= tmsethread.create(@execute);
 RTLeventResetEvent(evPauseImage); // to pause the thread
end;

procedure tanimfo.onpaint(const Sender: twidget;
                   const acanvas: tcanvas);
begin
isbuzy := true;
...
// all the calculation of canvas tpaintbox1 with parameters from a other form
...
isbuzy := false;
end;

function tanimfo.execute(thread: tmsethread): integer;
begin
repeat
if (isbuzy = false) and (visible = true) then
begin
tpaintbox1.invalidate;
RTLeventResetEvent(evPauseimage);
RTLeventSetEvent(evPauseImage); // pause the loop
end;
 until status = 0;
end;

```

And in the main-audio thread loop:

```
   ...
    if isbuzy = false then RTLeventSetEvent(evPause); // to resume pause
  ...
```

?

**Comment by fredvs** [comment]
Re-hello.

I did re-write the code, maybe? now the `onpaint` event is part of the thread.

First, no more assignation for the  `onpaint` event of the tpaintbox1 object, it will be done by the thread.

So the execute() method of the thread is this:

```
function tanimfo.execute(thread: tmsethread): integer;
begin
repeat

if (isbuzy = false) and (visible = true) then
begin
  application.queueasynccall(@InvalidateImage);
  RTLeventResetEvent(evPauseImage);
  RTLeventWaitFor(evPauseImage);
  RTLeventSetEvent(evPauseImage); // to pause thread  
end;
 until statusanim = 0;
end;
```

and the synchro procedure of object is this:

```
Procedure timagedancerfo.InvalidateImage;
begin
onpaintimage(tpaintbox1, tpaintbox1.getcanvas);
end;
```

And the onpaint procedure is:

```
procedure tanimfo.onpaint(const Sender: twidget;
                   const acanvas: tcanvas);
begin
isbuzy := true;
...
// all the calculation of canvas tpaintbox1 with parameters from a other form
...
isbuzy := false;
end;
```

Imho, the drawing should be part of the thread now.

It works ok, but when full screen, all other animations are slower too.

**Comment by circular17** [comment]
Honestly I don't know. I don't know what you are trying to achieve.

I am not sure one can safely use the canvas in a thread. I would say that what can safely be done is to prepare the bitmap to be displayed in a thread then invalidate the display in an asynchronous call. And by invalidating I do not mean redrawing but querying the paint event. And in the OnPaint to display the bitmap on the canvas.

**Comment by fredvs** [comment]
>  don't know what you are trying to achieve.

It is a "Dancing Image", a image that change regarding the music parameters (volume and frequencies).
https://github.com/fredvs/strumpract

In the code first code I give, the invalidate of the paintbox is done inside the thread.

In the second code I give, the calculation of the bitmap (onpaint) is done by a asynchronous call from the thread.

Both are working (but makes the rendering of the main thread slower).

So, to resume, I want to archive a way to draw the "Image Dancer" without slowing the drawings of the main thread.

**Comment by fredvs** [comment]
Hello, guess what... it is me again!

Bon, I did a other:

Running 2 instances of StrumPract.

One is playing a song, with VU meters enabled and spectrum in main thread and in a other thread the Image Dancer in a full-screen.

Both animations of VU meters and full screen are slower.

But, in the other instance that only play a song with VU meters enabled and spectrum in main thread but without Image Dancer, the VU are fast and not affected by the other instance.

So it seems to me that in the first instance, the main thread is not totally independent from the Image Dancer thread.

I am sorry to annoy you with that, but I like to understand how things work.

**Comment by circular17** [comment]
Yeah I am not sure how it works or if it is possible to draw faster using multiple threads. You can prepare the image with multiple threads, but the actual drawing of the bitmap on the canvas, I am not sure you can make it faster. It is a bit like putting a big image in fullscreen, it takes time.

**Comment by fredvs** [comment]
What I do not really understand is the independence of multiple thread in a fpc gui application.

Afaik, a application is by himself a independent thread.

Like explained in previous thread, it seems that the only way to have independent drawing is to create 2 applications and find a external way to share the parameters of the "Main Audio" application to the "Dancing Image" application.

I was hoping to do all in the same application using a thread but it affect the result of rendering of the "Main Audio" form.

**Comment by fredvs** [comment]
> or if it is possible to draw faster using multiple threads.

That is not really the problem.
I assume that it depends of lot of things, including the size of the canvas, the graphic card,...

The thing is that I want a independent drawing, that does not affect drawing of other forms.

**Comment by jdelauney** [comment]
Hi, Jonas, Hi Fred, interesting discussion, i think i understand your problem Fred. 

First Jonas, I apologize in advance, I will talk a little about my project, and I especially do not want to compete with BGRABitmap which I love.

And also sorry for my english.

Fred, if I understand correctly in your application, in the main window you play music or other audio source via one thread and you display your 'vu meter' in another thread. And now you want to display a 'WinAmp' animation in a secondary window via a third thread. It's just ?

The problem in my humble stems from the use you make of your threads.
 In the thread where you play your music you extract the values ​​of 'peak' for the 'vu meter' via your second thread you access this value and in the 3rd you also want access to this value at the same time. When you use threads you have critical sections which 'lock / unlock' access to variables in writing and reading. So this why tou lag time and yours drawing become slower.
This is what I will do. Initially, I will manage the rendering of the 'vu meter' directly in the thread through which the music is played.
When this one has read the value of 'peak', and I will copy it to another variable, in a common unit, and I will trigger an event to the second window to request the refresh of the animation. This will reduce the 'lag' times. I will also add a boolean flag in the second window to determine if the rendering is finished,  to avoid a bottleneck when the value of the 'peak' changes

Another thing is better to use 'Repaint' than 'Invalidate'. And then of course the speed will depend on the complexity of your animation.

Even if you use a 'thread' to retrieve the values ​​of 'peak' to optimize the rendering speed, you can try to use parallelization (with the Lazarus MultiThread package for example, or my unit https://github.com/jdelauney/BZScene/blob/master/Source/Core/BZParallelThread.pas. And this is a sample on how you can use it https://github.com/jdelauney/BZScene-Demoscene-samples/tree/master/Bump for improving time of rendering. It can be more than x3) 

If not, you have another possibility is to separate the rendering of your animation in 4 specialized threads. Each thread manages part of the final bitmap. I use this technique to bypass critical sections, because for rendering some software shader alla "GLSL Shader" i need to read or write some values at the same time  and it's not possible with parallelization. You can take a look at my TBZBitmapShaderThreadRasterizer in https://github.com/jdelauney/BZScene/blob/master/Source/Engine/BZBitmapRasterizer.pas for see how i do. It improve time of rendering by x3 or more, always depends of the calculus complexity.

Normally, playing a sound should occupy a maximum of 10 to 15% of the CPU.

As an example I made 2 short videos on one of my personal projects.
It is under windows and with the display of information on the use of the cpu.

The music is played via an 'a specialized "Thread Timer"  (https://github.com/jdelauney/BZScene/blob/master/Source/Components/Tools/BZCadencer.pas) for animation progression' and the rendering is also done directly in this one.
The music is player with the help of "OpenAL library" 

The project is not yet very optimized. Each part is drawn in a 'bitmap' buffer one by one (the background, the menu background, then each button and finally the mouse cursor).

Look at FPS and CPU usage.

In the 1st video, the background is not animated
https://www.youtube.com/watch?v=lZ34A1xyNtA

In the 2nd video, the background is animated, via one of my shaders. 
https://www.youtube.com/watch?v=I2gO2ZpLjzM

We can see the difference the FPS drops by 30 'frames' and the CPU usage increases up to 20%.
 But we still have the impression of having a more or less 'fluid' animation
Namely the animation of the shader is rendered in a buffer twice smaller (512x384) then resize to 1024x768. Without the use of thread the fps should less than 4 frames per second.

I hope it will help you.

Best regards

Jérôme

**Comment by fredvs** [comment]
Hello Jérôme.

Wow for your answer.

> Fred, if I understand correctly in your application, in the main window you play music or other audio source via one thread and you display your 'vu meter' in another thread.

Yes, nearly, here the main window plays music via one thread and the 'vu meter' are painted in a form via a "synchronized method" in the audio-thread.

It works perfectly and the painting of VU dont disturb at all the audio-thread.

> And now you want to display a 'WinAmp' animation in a secondary window via a third thread. It's just ?

Yes, it is that that I want but without slowing the synchronized method and, of course, without disturbing the audio-thread..

> In the thread where you play your music you extract the values ​​of 'peak' for the 'vu meter' 
> via your second thread you access this value and in the 3rd you also want access to this value at the same time.

Yes, but in my case the second thread is the main thread and yes, I would like to use those values ​​of 'peak' for the 'vu meter' and spectrum frequencies for the ( for me) second thread  'WinAmp' animation in a independent other window.

> Another thing is better to use 'Repaint' than 'Invalidate'.

It is what I use in the synchro method:

```
function tanimfo.execute(thread: tmsethread): integer;
begin

repeat

if (isbuzy = false) and (visible = true) then
begin
application.queueasynccall(@InvalidateImage);
 RTLeventResetEvent(evPauseImage);
RTLeventWaitFor(evPauseImage);// is there a pause waiting ?
RTLeventSetEvent(evPauseImage);  // pause the thread 
end;
sleep(10);
 until statusanim = 0;

end;
```

```
Procedure timagedancerfo.InvalidateImage;
begin
onpaint_imagedancerfo(tpaintbox1, tpaintbox1.getcanvas);
end;
```

> Your propositions...

Many, many thanks, I will deep study this.
Write you later.

Fre;D

**Comment by fredvs** [comment]
Re-hello Jérôme.

> When this one has read the value of 'peak', and I will copy it to another variable, in a common unit, and I will > trigger an event to the second window to request the refresh of the animation.

Ho, this one I like very much and logically indeed using the same variable should disturb the synchronization of the VU/Spectrum peaks.

I am not with my machine now, but this one I want to try asap.
Like said, write you later.

Fre;D

**Comment by fredvs** [comment]
Hello Jérôme.

Hum, I dont trust too much in parallelism, I would prefer to take simpler solution...

Anyway, I deal with sound samples directly via PortAudio library and dont use any timers, the timer is the sound.
I fear that It would very difficult to make 2 different "onPaint" independent on the same application.

I just discover a mse OpenGl widget, ready to use that uses OpenGL for animation.
https://github.com/mse-org/mseide-msegui/issues/20#issue-705001203

It is incredibly fast and dont disturb the VU meters, even if the OpenGL form is part of the application and uses the audio-variables, even in full-screen. 

Maybe a solution.

**Comment by fredvs** [comment]
I confirm, using `OpenGL` is a good the solution, it does not affect the "onpaint" of other forms, is very fast even on full-screen.

I did add a "Dancing Square" in Strumpract that uses OpenGL.
It lives perfectly with the other BGRABimap animations like Fractal Tree and Super Formula.

But I have to admit that the OpenGL anim is faster and does not makes other "onpaint" slower.

That said, sure both OpenGL and BGRABitmap have advantages and the speed is not always needed.

To resume, for me, mse user, it is perfect I have both of best world.

Many thanks for this great discussion very helpful. 

Fre;D

**Comment by fredvs** [comment]
As bonus, a video showing the Dancing Square in action:

[image_dancer_square.mp4.zip](https://github.com/bgrabitmap/bgrabitmap/files/5251045/image_dancer_square.mp4.zip)

**Comment by fredvs** [comment]
Solution was found here:
https://github.com/bgrabitmap/bgrabitmap/issues/128#issuecomment-697703741

**Comment by fredvs** [comment]
Hello.

Sorry but I cannot close this issue without closing all "mal-entendus".

BGRABitmap is very fast and has nothing to envy to OpenGL and his speed.

In prevous post here was a audio-video of OpenGL animation in action:
[image_dancer_square2.mp4.zip](https://github.com/bgrabitmap/bgrabitmap/files/5251057/image_dancer_square2.mp4.zip)

Here  a audio-video of Fractal Tree BGRABitmap  animation.
You will note that both are fluent and do not affect rendering of other forms.
[image_dancer_fractaltree2.mp4.zip](https://github.com/bgrabitmap/bgrabitmap/files/5270330/image_dancer_fractaltree2.mp4.zip)
