### ISSUE TITLE
built into Lazarus 

### ISSUE THREAD

**Issue by Reaper10** [bgrabitmap/bgrabitmap#143]
///can you built this into Lazarus fpc?

**Comment by lainz** [comment]
Lazarus is not us. It's just a tool to project. We're our own team not
associate with Lazarus. We use Lazarus because it's free and open 24 hs a
day. And you can talk with them in some terms. But adding this into Lazarus
means work forever with Lazarus projects. The real thing is to open new
frontiers.

**Comment by circular17** [comment]
Another problem is that it is complicated to update a library that is part of fpc or Lazarus. With a separate package, it is much easier to provide new versions and bug fixes.
