### ISSUE TITLE
Wiki (FPC site): method InvalidateBitmap

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#165]
Subj method is mentioned only in 'direct pixel access' part of the wiki.
https://wiki.freepascal.org/BGRABitmap#Direct_access_to_pixels
 Pls write about it more info? when it's needed etc.

**Comment by circular17** [comment]
Basically, BGRABitmap can store an image that is not as such drawable, not a bitmap object of the system. In order to keep track of changes, the function InvalidateBitmap is called whenever pixel data is modified. Then when the bitmap object is requested, the library knows that it needs to be rebuilt.

To sum up, the only time a regular user would call this function is after accessing Data / ScanLine directly and before drawing the bitmap or requesting the bitmap object.
