### ISSUE TITLE
cannot compile the 'master' branch on last Laz release 3.0RC1

### ISSUE THREAD

**Issue by Alexey-T** [bgrabitmap/bgrabitmap#214]
@mix-7 gave me this log, he uses Lazarus 2.2.6.

```
/home/one/cudatext_up/src/bgrabitmap/bgrabitmap/generatedunicode.inc(406,1) Warning: (5059) Function result variable does not seem to be initialized
/home/one/cudatext_up/src/bgrabitmap/bgrabitmap/bgraunicode.pas(376,88) Hint: (5024) Parameter "endOfSequence" not used
/home/one/cudatext_up/src/bgrabitmap/bgrabitmap/bgraunicode.pas(537,87) Hint: (5024) Parameter "endOfSequence" not used
(3104) Compiling bgramultifiletype.pas
(3104) Compiling bgrautf8.pas
/home/one/cudatext_up/src/bgrabitmap/bgrabitmap/bgrautf8.pas(10,72) Fatal: (10022) Can't find unit lazutf8classes used by BGRAUTF8
Fatal: (1018) Compilation aborted
```

**Comment by fredvs** [comment]
Sorry to be the boring one always repeating the same song but what about this ?: https://github.com/bgrabitmap/bgrabitmap/issues/201#issuecomment-1595318844

**Comment by circular17** [comment]
Ok, I am checking with all version of Lazarus to see if they compile dev-bgrabitmap and master branches.

Lazarus 1.6.4 (with FPC 3.0.2) cannot compile because "specialize" keywords is not known to the compiler (wiki page https://wiki.freepascal.org/Generics says generics were implemented in FPC 2.2 but that does not seem the case to me).

Lazarus 1.8.4 (with FPC 3.0.4) cannot compile because "specialize" keywords is not known to the compiler.

Lazarus 2.0.10 (with FPC 3.2.0) compiles dev-bgrabitmap and master successfully.

Lazarus 2.2.2 (with FPC 3.2.2) compiles dev-bgrabitmap and master successfully.

Lazarus 2.2.6 (with FPC 3.2.2) compiles dev-bgrabitmap and master successfully.

Lazarus 3.0RC1 (with FPC 3.2.2) compiles dev-bgrabitmap successfully but not master branch. So I suppose @mix-7 has this version.

I will release a new version of BGRABitmap (11.5.5) to have the fix for the "classes" unit.

**Comment by circular17** [comment]
I don't want to duplicate FreeTypeLaz package. Though for MSEgui, you can copy its files along with required LazUtils files, in one directory making an independant FreeType implementation. Maybe with some work, you could remove more files and depend on BGRAUTF8 instead. But I am not sure that's even necessary.

**Comment by circular17** [comment]
About the the initial topic, I've published a new version of BGRABitmap that fixes the problem:
https://github.com/bgrabitmap/bgrabitmap/releases/tag/v11.5.5

**Comment by fredvs** [comment]
>Though for MSEgui, you can copy its files along with required LazUtils files

Of course, sorry to not have think about this, yes, good idea, I will do that way.
And in _/mseide-msegui/lib/common/lazfont_  so even no need to tweak parameters at compilation.

Of couuuuurse with all mentions to Lazarus, the licence, the many thanks, ...

Sorry for the noice.

**Comment by fredvs** [comment]
In attachment, **lazutf8.pas** in one unique file that include all the units and .inc needed.
For Windows and Unix os.
[lazutf8.pas.zip](https://github.com/bgrabitmap/bgrabitmap/files/12306269/lazutf8.pas.zip)

**Comment by fredvs** [comment]
Yes, too big and not needed any more! : https://github.com/bgrabitmap/bgrabitmap/issues/139#issuecomment-1672184739

So, no lazutf8.pas in msegui source...

;-)
