### ISSUE TITLE
Function 'round' causing problems

### ISSUE THREAD

**Issue by anjemor** [bgrabitmap/bgrabitmap#238]
The function is not doing what you think! It is 'banker rounding' and only good in such a context.
Unfortunately you have to use `floor (x + 0.5)`. 

The problems for me occur when using text functions like TextRect or DrawShadow. There I noticed, that text is not correct centered or shadows are one pixel off, which looks terrible for my buttons:
![TextRectError](https://github.com/bgrabitmap/bgrabitmap/assets/46479728/8ef55b0f-1993-4d32-ad31-2266d1de454a)
(1st row `floor`, 2nd row `round`)

**Comment by circular17** [comment]
Hi anjemor,

Yes, round is indeed the banker one. Not sure though at what point it generates an offset not to your taste. Can you show me the lines of code you would like to change?

Regards

**Comment by anjemor** [comment]
Sure.
## TextRect
![TextRectError](https://github.com/bgrabitmap/bgrabitmap/assets/46479728/650ebcce-8953-4667-b5f6-b044d68f0faa) 
Same arguments, but different widths. Not to my taste.
BGRAText, line 1234: 
`Point(round((xf - lim.Left)*sizeFactor), round((yf - lim.Top)*sizeFactor)),`
## TextShadow
![TextShadowError12](https://github.com/bgrabitmap/bgrabitmap/assets/46479728/7349cc3a-c1d3-4b49-99b4-3b86be5b9a12)
AOffsetY is the offset of the shadow. With a value of zero it should be behind the text. But depending on the AHeight argument and the rounding error it is off. Not to my taste.
BGRATextFX, line 237: 
`y := round( yf + diffCenter );`
## round
It's a mystery to me why you want to continue using this function. Let's take a closer look at the results in comparison:
#### round (0..9 / 2)
`0 0 1 2 2 2 3 4 4 4`
#### floor (0..9 / 2)
`0 0 1 1 2 2 3 3 4 4`
`floor` is obviously mathematical correct. `round` is ok when you not dividing by 2, but don't use it in moon landing software ...

**Comment by fredvs** [comment]
OK, I am converted, I will also  use **floor()** for dealing with audio integer-samples calculation.
Thanks for the tip.

**Comment by circular17** [comment]
Hi @anjemor,

The position of the shadow when using `TextRect` and `TextShadow` is not consistent. So I agree it would be better to change that.

I would not say I want to use `round` and I am aware that the result can be surprising. I don't think either that we must use `floor` all the time.

Let's think about it. When we would like an integer that approximates one float, there isn't a reason to round up or down. But when used multiple times, there are some things to consider.

The `round` function in Pascal follows the same convention as IEEE 754 rounding, called 'banker rounding' as you mentioned. It is also called 'statistical rounding'. The idea is that by rounding towards even number, no direction is preferred. So when summing a lot of numbers that have been rounded, the value is stable. When always rounding up, in this case the sum could be overestimated.

The case we're interested in here is when there are multiple rounding and that we need to direction of rounding to be consistent. In this case, this can be done by having the rounding always in the same direction, for example rounding up as you suggested.

I prefer in the code to write `round` as it expresses better the intent than `floor(... + 0.5)`. But we need to go beyond code esthetics here. Still I think that introducing a function to do that would could make things clearer. So now what name would be suitable?

There are various [rounding methods](https://en.wikipedia.org/wiki/Rounding), and among those:
- to round up: to take the ceiling as with `ceil(x)`
- to round half up: to round up when it reaches half as with `floor(x + 0.5)`

So a rather unambiguous name could be `RoundHalfUp` but it is a bit long. I suppose that `RoundUp` would be ok because there is already a `ceil` function so it is understandable that what we mean here is "round half up".

What do you think?

**Comment by DomingoGP** [comment]
Hi

I would suggest to use **Rounding half away from zero** since it treats positive and negative values symmetrically,
I expect that Round(1.5) = 2 and Round(-1.5)= -2

In my code I use RoundMath as name but other proposed name is RoundISO7185

see:
https://wiki.freepascal.org/Comparison_of_approaches_for_rounding_to_an_integer

Regards
Domingo

```pascal
function RoundMath(aV:double):int64;overload;
begin
  if aV>=0 then
    result:=Trunc(aV+0.5)
  else
    result:=Trunc(aV-0.5);
end;

function RoundMath(aV:single):int64;overload;
begin
  if aV>=0 then
    result:=Trunc(aV+0.5)
  else
    result:=Trunc(aV-0.5);
end;
```

**Comment by circular17** [comment]
Hi @DomingoGP 

Thanks for popping by.

Regarding rounding away from zero, I would not think it applies to the case mentioned by @anjemor because even if coordinates are negative, we would still want to have the shadow with the same offset and that would not be guaranteed with rounding away from zero.

For example, if the text coordinate is (0.5, 0.5) and shadow is at (+1, +1), we would get the text at (0.5, 0.5) => (1, 1) and the shadow at (1.5, 1.5) => (2, 2). Now if the text coordinate is (-0.5, -0.5), we would get the text at (-0.5, -0.5) => (-1, -1) and the shadow at (0.5, 0.5) => (1, 1).

There are probably use cases where rounding away would be useful. Would you have an example in mind?

Regards

**Comment by DomingoGP** [comment]
> I would not think it applies to the case mentioned

You are right, sorry for the noise.

> Would you have an example in mind?

Right now I can't think of any related to graphics programming.

Regards.

**Comment by circular17** [comment]
Hi @DomingoGP,

Even if your suggestion might not fit with the current issue, it's great to see different perspectives. The subject is not as obvious as it may seem. So thanks again for sharing your thoughts and keeping the discussion going.

Warm regards

**Comment by anjemor** [comment]
`RoundUp` sounds like it is doing `Ceil`, if you don't know this discussion - and is also the name of a herbicide. Than rather **`RoundHalf`**.
Thanks for the efforts.

**Comment by circular17** [comment]
Hi @anjemor,

While I don't feel like `RoundUp` sounds like `Ceil`, in particular in the context of Pascal, I would agree that it may be interpreted that way by native English speakers and a bit confusing regarding rounding terminology. The name `RoundHalf` in my view wouldn't either express either the idea because it doesn't specify the direction.

`RoundHalfUp` would remain a good choice for expressing the idea without ambiguity. Another possibility would be to call it `HalfUp`. This would address the concern of finding a name that is both meaningful for English speakers and succinct enough for practical use in programming, striking an optimal balance between descriptiveness and conciseness.

**Comment by anjemor** [comment]
Yes, indeed. And very short! I will use it in my programs also!

**Comment by circular17** [comment]
Hi @anjemor 

I've added the function on [dev](https://github.com/bgrabitmap/bgrabitmap/tree/dev-bgrabitmap) branch (ee27e440911335456fed58645073442e901bc14c) and applied it to `BGRAText` and `BGRATextFX` units. Can you give it a try?

Note: the `HalfUp` / `HalfUp64` functions are in `BGRABitmapTypes` unit.

Regards

**Comment by fredvs** [comment]
Hum, lot of embarras du choix here!

Should I use round(), floor() or halfup() for integer samples?
(I agree that you must have extraordinary good ears and headphones to feel the difference.)

**Comment by circular17** [comment]
For audio samples, I suppose the best would be `RoundMath` function proposed by @DomingoGP . Indeed, at the same time, you would like the value to increase progressively, and at the same time you would like them to remain centered on zero. So I guess we found a use case for this function.

For coordinates on a plane, `RoundUp` is probably the best, because you don't want the rounding to change around zero.

And when computing sums, if the items are to be rounded, then good old `Round` is better.

Wow rounding is quite a story!

**Comment by fredvs** [comment]
Ooook.

So, many thanks  @DomingoGP, _uos_ will use **RoundMath()**.

**Comment by anjemor** [comment]
> added the function on [dev](https://github.com/bgrabitmap/bgrabitmap/tree/dev-bgrabitmap) branch (https://github.com/bgrabitmap/bgrabitmap/commit/ee27e440911335456fed58645073442e901bc14c)

Thanks, the changes are working!

**Comment by circular17** [comment]
Wonderful! Thanks for the confirmation
