### ISSUE TITLE
JoinStyle pjsRound not working for 180 degree turns

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/bgrabitmap#39]
Copied from: https://sourceforge.net/p/lazpaint/bugs/23/

At least with procedure DrawPolyLineAntialiasAutocycle, when using pjsRound JoinStyle, 180 degree joins are drawn flat while all other joins are drawn round.

**Comment by zoltanleo** [comment]
Hi.
I get error compiling with message
`bgratextbidi.pas(229,67) Error: Only static methods and static variables can be referenced through an object type`
with lazarus trunk r.60137 & fpc trunk r.40898.

I think that this is due to the latest changes in the fpc code, such as http://wiki.freepascal.org/User_Changes_Trunk

**Comment by circular17** [comment]
fixed in version 10.5
