### ISSUE TITLE
bgrabitmap logo

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#81]
I noticed that bgra doesnt have a logo, only the lazpaint one is being used, we need a logo?

**Comment by lainz** [comment]
This is my first try:
![bgrabitmap](https://user-images.githubusercontent.com/4131395/69914796-22e5ff80-1427-11ea-925c-1010003a43cd.png)

**Comment by circular17** [comment]
Pretty nice indeed !

**Comment by lainz** [comment]
Thanks =)

Here are the logos in SVG format, seems that the vector program exporter exports some things as encrusted bitmaps.
[logos.zip](https://github.com/bgrabitmap/bgrabitmap/files/3908844/logos.zip)

**Comment by circular17** [comment]
Hmm strange indeed. What is the vector program you're using?

**Comment by lainz** [comment]
I used Affinity Designer, but I will try using other like Inkscape that has SVG as native format.

The shadows and the inner shadow was rasterized.

I think I can get a similar result using a gradient for the inner shadow, For the text shadow duplicating text and using filter based blur that Inkscape has.

**Comment by lainz** [comment]
This is all vector now, with Inkscape, it uses filters instead of Bitmaps for text shadow and inner shadow of the colored rectangles.
[logos_inkscape.zip](https://github.com/bgrabitmap/bgrabitmap/files/3914407/logos_inkscape.zip)

Tested the same effects in Adobe Illustrator and also produces a file with bitmaps, so seems that is more common that we think.

**Comment by circular17** [comment]
Cool. Looking in the files, I still found some images in the def section, though they do not seem to be used. Probably they stayed from previous version. I removed then and it looks the same.

I see. I suppose using a bitmap for a shadow is not too bad in the sense that resampling it doesn't different. When resampling things get blurred but a shadow is blurred so that's not visible.

[logo_no_image.zip](https://github.com/bgrabitmap/bgrabitmap/files/3917385/logo_no_image.zip)
![bgracontrols](https://user-images.githubusercontent.com/9092455/70065150-e95df180-15ea-11ea-8fdf-eeebb94be246.png)

**Comment by lainz** [comment]
OK cool. It looks somewhat different, changing the drop shadow (that works like an inner shadow) effect transparency to 70% looks somewhat like the original picture. But I let you change that, with Inkscape at the level you think looks best.

**Comment by lainz** [comment]
I'm already using it in bgracontrols repository. Well I close this if we need to change the logo in the future we can open a new bug report.

**Comment by circular17** [comment]
I like the logo, though I am not sure where to put it.

**Comment by lainz** [comment]
I for example put it in the readme file.

**Comment by circular17** [comment]
Hmm ok. I renamed the readme to md extension (as it seems to allow syntax for images) and added the image. Also added in the wiki.

**Comment by lainz** [comment]
Cool thanks.
