### ISSUE TITLE
Multithreaded filter

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgrabitmap#83]
This looks interesting:
https://itk.org/Doxygen/html/ThreadingPage.html

> Note that the "entire" input and "entire" output images (i.e. what would be available normally to the GenerateData() method, see the discussion on Streaming) are available to each call of ThreadedGenerateData(). Each thread is allowed to read from anywhere in the input image but each thread can only write to its designated portion of the output image.
> 
> The output image is a single contiguous block on memory that is used for all processing threads. Each thread is informed which pixels they are responsible for producing the output values. All the threads write to this same block of memory but a given thread is only allowed to set specific pixels.

I mean for normal filters like grayscale this will not be much faster (or maybe yes on really big images?). But for Blur filter having a MultithreadBlur can make it really faster.

**Comment by lainz** [comment]
Here I tried
https://github.com/bgrabitmap/multithreadedfilter

But I get an exception, that i'm out of memory for creating the thread (like when I resize a lot the form). But it works at least is a start.

**Comment by lainz** [comment]
Now I fixed it, but the main form is not very fast or responsive, maybe it can be fixed with another technique.

**Comment by lainz** [comment]
I close this since maybe it's good to process images in a background process, is not good for displaying on screen that's one if not the main way to use bgrabitmap.

Is faster using a single thread, at least on my machine. So don't worth the time trying if even the grayscale filter works badly.

**Comment by lainz** [comment]
I fixed it, with 2 threads now works fast and fine!
https://forum.lazarus.freepascal.org/index.php/topic,48085.msg345826.html#msg345826

**Comment by circular17** [comment]
For blur, it is a bit more complicated than grayscale. It cannot be done in-place because the content of pixels influence other pixels. For example, if the first thread changes pixels at the bottom of its target rectangles before the second thread reads those, then the blur result would be different.

Then, the current algorithm for blur would not be adapted, because the source rectangle for pixels is wider than the destination rectangle. For example, if the second thread target area starts at row 100 and the blur radius is 10, then it needs to read pixels from row 90.

So one would need to write a new version of the blur algorithm that can take two rectangles as input, the source and the destination rectangle.

Second difficulty, in order to optimize blur, I've approximated it by a series of box blur one on another:
```
  if radiusX*radiusY >= 100 then
  begin
    tempDest := ADestination.NewBitmap;
    tempDest.SetSize(ADestination.Width,ADestination.Height);
    FilterBlurBox(bmp,bounds,radiusX/3.2,radiusY/3.2,tempDest);
    FilterBlurBox(tempDest,bounds,radiusX/2.9,radiusY/2.9,ADestination);
    FilterBlurBox(ADestination,bounds,radiusX/3.2,radiusY/3.2,tempDest);
    FilterBlurBox(tempDest,bounds,radiusX/2.3,radiusY/2.3,ADestination, ACheckShouldStop);
    tempDest.Free;
    exit;
  end; 
```

In this case, each thread need to wait for the others to have completed before going to the next box blur.

**Comment by lainz** [comment]
Oh I see, well, it was a good experiment anyways =)

**Comment by circular17** [comment]
Yeah threads are interesting. :)
